import { execFile } from "child_process";
import { promisify } from "util";
import fs from "fs/promises";
import path from "path";
import crypto from "crypto";

const execFileAsync = promisify(execFile);

export async function runCppConverter(cadData: any[]) {
  const reqId = crypto.randomUUID();
  const tmpDir = path.join(process.cwd(), "tmp");
  const inPath = path.join(tmpDir, `input_${reqId}.json`);
  const outPath = path.join(tmpDir, `output_${reqId}.obj`);
  
  // Point to the compiled binary inside your Next.js project
  const exeName = process.platform === "win32" ? "MiningMesher.exe" : "MiningMesher";
  const exePath = path.join(process.cwd(), "bin", exeName);

  try {
    // 1. Prepare temporary directory
    await fs.mkdir(tmpDir, { recursive: true });

    // 2. Clean duplicate consecutive vertices (Ported from server.js)
    const processedData = cadData.map(obj => {
      const properties = obj.properties || obj; // Handle nested properties
      if (properties.FlattenedVertices && Array.isArray(properties.FlattenedVertices)) {
        const cleaned = [properties.FlattenedVertices[0]]; 
        for (let i = 1; i < properties.FlattenedVertices.length; i++) {
          const curr = properties.FlattenedVertices[i];
          const prev = properties.FlattenedVertices[i - 1];
          if (curr[0] !== prev[0] || curr[1] !== prev[1] || curr[2] !== prev[2]) {
            cleaned.push(curr);
          }
        }
        return { ...properties, FlattenedVertices: cleaned };
      }
      return properties;
    });

    // 3. Write data to a temporary JSON file for C++ to read
    await fs.writeFile(inPath, JSON.stringify(processedData));

    // 4. Execute the C++ Binary
    console.log(`[Bridge] Executing C++ Mesher for ${processedData.length} fragments...`);
    await execFileAsync(exePath, [inPath, outPath]);

    // 5. Read the resulting OBJ file generated by C++
    const objContent = await fs.readFile(outPath, "utf8");

    // 6. Parse OBJ into flat arrays for Database/Three.js compatibility
    const vertices: number[] = [];
    const indices: number[] = [];
    const lines = objContent.split("\n");

    for (const line of lines) {
      const parts = line.trim().split(/\s+/);
      if (parts[0] === "v") {
        vertices.push(parseFloat(parts[1]), parseFloat(parts[2]), parseFloat(parts[3]));
      } else if (parts[0] === "f") {
        // OBJ indices are 1-based, WebGL/Three.js expects 0-based
        indices.push(parseInt(parts[1]) - 1, parseInt(parts[2]) - 1, parseInt(parts[3]) - 1);
      }
    }

    console.log(`[Bridge] Success: Parsed ${vertices.length / 3} vertices and ${indices.length / 3} faces.`);
    
    // Return the clean data structure expected by block_meshes table
    return { vertices, indices };

  } catch (error) {
    console.error("[Bridge] C++ Execution Error:", error);
    return null;
  } finally {
    // 7. Always clean up temporary files so your server disk doesn't get full
    await fs.unlink(inPath).catch(() => {});
    await fs.unlink(outPath).catch(() => {});
  }
}